FROM puckel/docker-airflow:1.10.9
RUN pip install pip --upgrade
RUN pip install pyopenssl --upgrade
RUN pip install requests
RUN pip install pandas
RUN pip install firebase-admin
RUN pip install tweepy